Repository Ricard-Garcia/php-employee-management-v2, pull requests merged in 2021-07, with the labels that each got.

#7 Feat/add mysql database
  config/db.php
  controllers/employeeController.php
  controllers/err.php
  controllers/loginController.php
  controllers/main.php
  db/db.sql
  index.php
  libs/Database.php
  libs/Router.php
  libs/avatarsApi.php
  libs/sessionHelper.php
  models/employeeManager.php
  models/loginManager.php
  resources/employees copy.json
  resources/employees.json
  views/dashboard.php
  views/employee.php
  views/imageGallery.php
Labels: enhancement

#8 Feat/add libs classes
  .gitignore
  config/constants.php
  controllers/ErrorController.php
  controllers/employeeController.php
  index.php
  libs/Controller.php
  libs/Model.php
  libs/Router.php
  libs/View.php
Labels: enhancement

#15 Feat/add header, footer and login and dashboard views
  assets/css/login.css
  assets/css/main.css
  assets/php/head.php
  config/constants.php
  controllers/DashboardController.php
  controllers/MainController.php
  controllers/loginController.php
  index.php
  libs/Router.php
  libs/avatarsApi.php
  views/dashboard.php
  views/dashboard/index.php
  views/footer.php
  views/header.php
  views/imageGallery.php
  views/login/index.php
Labels: enhancement

#17 fix: fixed Router class url
  controllers/MainController.php
  controllers/employeeController.php
  controllers/loginController.php
  libs/Router.php
  libs/View.php
  views/employee.php
  views/employee/index.php
Labels: enhancement

#22 Feat/refactor router
  .htaccess
  assets/css/main.css
  config/baseConstants.php
  config/constants.php
  config/db.php
  controllers/DashboardController.php
  controllers/ErrorController.php
  controllers/GeneralController.php
  controllers/IndexController.php
  controllers/MainController.php
  controllers/employeeController.php
  controllers/loginController.php
  controllers/main.php
  index.php
  libs/Controller.php
  libs/Database.php
  libs/Model.php
  libs/Router.php
  libs/View.php
  models/GeneralModel.php
  models/IndexModel.php
  views/dashboard/index.php
  views/employee/index.php
  views/error/index.php
  views/footer.php
  views/header.php
  views/login/index.php
  views/templates/head.php
Labels: bug

#25 Feat/load jsgrid data
  .DS_Store
  assets/css/main.css
  assets/html/header.html
  assets/js/jsgrid.js
  config/db.php
  controllers/EmployeesController.php
  controllers/ErrorController.php
  controllers/GeneralController.php
  db/db.sql
  index.php
  libs/Controller.php
  libs/Database.php
  libs/Router.php
  models/EmployeesModel.php
  models/GeneralModel.php
  models/employeeManager.php
  views/employee/index.php
  views/error/index.php
  views/header.php
  views/login/index.php
  views/templates/head.php
Labels: bug, enhancement

#30 Feat/create and update employee
  assets/js/jsgrid.js
  controllers/EmployeesController.php
  models/EmployeesModel.php
  views/employee/index.php
  views/login/index.php
Labels: enhancement

#32 Feat/logout
  assets/css/main.css
  assets/html/header.html
  controllers/EmployeesController.php
  controllers/IndexController.php
  controllers/LoginController.php
  controllers/SessionController.php
  index.php
  libs/Controller.php
  libs/Router.php
  models/LoginModel.php
  views/header.php
  views/login/index.php
Labels: enhancement

#35 fix: solved gender select bug
  assets/js/index.js
  assets/js/jsgrid.js
  models/loginManager.php
  views/employee/index.php
Labels: bug, enhancement

#36 Feat/redirect after create employee
  controllers/EmployeesController.php
  controllers/IndexController.php
  libs/Router.php
  libs/sessionHelper.php
  models/IndexModel.php
Labels: bug

#40 feat: added README
  README-Old.md
  README.md
  assets/.DS_Store
  resources/images_mock copy.json
  resources/images_mock.json
  resources/users copy.json
  resources/users.json
Labels: documentation

#39 Fix: solved bug when adding employee via jsgrid
  assets/html/footer.html
  assets/html/header.html
  assets/js/jsgrid.js
  controllers/EmployeesController.php
  models/EmployeesModel.php
  views/employee/index.php
Labels: bug, enhancement

#41 Feat/error control router
  assets/js/navbar.js
  libs/Router.php
Labels: enhancement

#42 feat: PDO Object seted to null
  libs/Database.php
Labels: enhancement

#43 fix: fixed link highlight logic
  assets/js/navbar.js
Labels: bug, enhancement
